# amlt debug launch.yaml
# amlt --pdb run launch.yaml
# amlt run launch.yaml

description: fMRI linear fit
environment:
  image: amlt-sing/acpt-2.2.2-py3.10-cuda12.1
  setup:
    - pip install -r requirements.txt --user
    - git clone https://github.com/csinva/imodelsX.git
    - pip install imodelsX/
    - pip install . --user

code:
  local_dir: $CONFIG_DIR/..


target:
  service: sing
  name: msrresrchvc
  # resource_group: gcr-singularity-lab
  workspace_name: gcrllama2ws

storage:
  output:
    storage_account_name: chansingh
    container_name: cs1
    mount_dir: /mntv1 # dir on the local machine

# sku options
# equivalences: mem x C x numcpus
# cpu jobs
# 10C3  # 4 cores, 30 GBs mem
# 8C7   # 8 cores, 56 GBs mem
# 8C15  # 15 cores, 120 GBs mem
# 8C30  # 30 cores, 240 GBs mem
# 8C60  # 60 cores, 480 GBs mem
# jobs:
# - name: run_fmri
#   process_count_per_node: 1
#   sku: E32ads_v5
#   command:
#   - echo "test"
# - name: run_fmri2
#   process_count_per_node: 1
#   sku: E32ads_v5
#   command:
#   - echo "test2"

# must end with just 'jobs:' for imodelsx
jobs: