# amlt debug launch.yaml
# amlt --pdb run launch.yaml
# amlt run launch.yaml

description: fMRI embedding extraction
environment:
  image: amlt-sing/acpt-2.2.1-py3.10-cuda12.1
  setup:
    - pip install -r requirements.txt --user
    - git clone https://github.com/csinva/imodelsX.git
    - pip install imodelsX/
    - pip install .

code:
  local_dir: $CONFIG_DIR/..


target:
  service: sing
  name: msrresrchvc
  resource_group: gcr-singularity-resrch
  workspace_name: msrresrchws

storage:
  output:
    storage_account_name: chansingh
    container_name: cs1
    mount_dir: /mntv1 # dir on the local machine

# sku options
# equivalences: mem x C x numcpus
# 10C3   E4ads_v5 # 30 GBs
# 8C7    E8ads_v5 # 56 GBs
# 8C15   E16ads_v5 # 120 GBs
# 8C30   E32ads_v5 # 240 GBs
# 8C60   E64ads_v5 # 480 GBs
# jobs:
# - name: run_fmri
#   process_count_per_node: 1
#   sku: E32ads_v5
#   command:
#   - echo "test"
# - name: run_fmri2
#   process_count_per_node: 1
#   sku: E32ads_v5
#   command:
#   - echo "test2"

# must end with just 'jobs:' for imodelsx
jobs: